logging:
  level: INFO

db:
  host: !ENV ${DB_HOST|127.0.0.1}
  port: !ENV ${DB_PORT|3306|int}
  user: !ENV ${DB_USER|root}
  password: !ENV ${DB_PASSWORD|root}
  name: !ENV ${DB_NAME|mediatorr}


sentry:
  dsn: !ENV ${SENTRY_DSN}

telegram:
  token: !ENV ${TELEGRAM_TOKEN}
  users:
    - !ENV ${TELEGRAM_CHAT_ID}

notifications:
  follow_check_interval: !ENV ${NOTIFICATIONS_CHECK_INTERVAL|2h}
  chat_id: !ENV ${TELEGRAM_CHAT_ID}

tmdb:
  image_prefix: https://image.tmdb.org/t/p/w500/
  token: !ENV ${TMDB_TOKEN}


qbittorrent:
  url: !ENV ${QBITTORRENT_URL|http://qbittorrent:8080}
  username: !ENV ${QBITTORRENT_USERNAME}
  password: !ENV ${QBITTORRENT_PASSWORD}

jackett:
  url: !ENV ${JACKETT_URL|http://jackett:9117}
  token: !ENV ${JACKETT_TOKEN}
