logging:
  level: INFO

db:
  path: db/database.db

sentry:
  dsn: https://9dbb8eeabf57429ca58e5e327b86d0f5@sentry.io/5009268

telegram:
  token: 965672840:AAEPqMkejPuGmTBPkEn6uHz5wQi5SQfI1LQ
  users:
    - 42246983

notifications:
  follow_check_interval: 2h
  chat_id: 42246983


tmdb:
  image_prefix: https://image.tmdb.org/t/p/w500/
  token: 5faf37a82fc681bbe1d2de068ff5b4f1


qbittorrent:
  url: http://qbittorrent:8080
  username: neronmoon
  password: 5588898

jackett:
  url: http://188.166.7.183:9117
  token: ucuegplk17nl8ls59cclgozil5azooev
